
[paths]
laz_path = "/home/timo/Media/Documents/tutkimus/Gälve_Nevia/Dataset/Santiago_urban-dataset_SUD/combined_MLS.laz"
output_dir = "coco_output_test"

[image]
# Optional: if omitted, defaults will be used
width = 1024
height = 128
max_range = 50
elevation_range = [-45, 45]

[sensor]
# Optional: if omitted, defaults will be used
sensor_orientation = [0.0, 0.0, 0.0]
use_trajectory_orientation = true

[processing]

sampling_points = 5


randomize = false
pos_perturbations =0
orientation_perturbations =0

rand_range_x = [-25,25]
rand_range_y = [-25,25]
rand_range_z = [-1,4]

rand_range_roll = [-10,10]
rand_range_pitch = [-15,15]
rand_range_yaw = [-180,180]
