
[paths]
#laz_path = "/home/timo/code/rangeImageGenerator/data/Segment_D.laz"
output_dir = "vt7_data_very_large"
laz_dir = "/home/timo/code/rangeImageGenerator/data/HaVa_Paikkatietoaineisto_EPSG_3067/250417_Hava_E18_Record062_250417_140207_Scanner_1.laz"
trajectory_dir = "/home/timo/code/rangeImageGenerator/data/HaVa_Paikkatietoaineisto_EPSG_3067/Trajectory - 250417_140207_Scanner_1.txt"

# laz_dir = "/home/timo/Documents/tutkimus/Gälve_Nevia/ouluZone/Ouluzone Data/LAS/Colored_LAS/Scanner_2"
# trajectory_dir = "/home/timo/Documents/tutkimus/Gälve_Nevia/ouluZone/Ouluzone Data/"
#laz_dir = "/home/timo/Media/Documents/tutkimus/Gälve_Nevia/HaVa_Paikkatietoaineisto_EPSG_3067/"
#trajectory_dir = "/home/timo/Media/Documents/tutkimus/Gälve_Nevia/HaVa_Paikkatietoaineisto_EPSG_3067"
[image]
# Optional: if omitted, defaults will be used
# width = 1024
# height = 128
# max_range = 50
# elevation_range = [-45, 45]

elevation_range  = [-45 ,45]
width= 1024
height= 128


[sensor]
# Optional: if omitted, defaults will be used
sensor_orientation = [0.0, 0.0, 0.0]
use_trajectory_orientation = true

[processing]
sampling_points = 100
skip_start = 500 # trajectory points to be skipped from the start
skip_end = 500   # trajectory points to be skipped from the end
stride = 500   # step size for trajectory

randomize = true
rand_range_x = [-3,3]
rand_range_y = [-3,3]
rand_range_z = [0.5,1.5]

rand_range_roll = [-10,10]
rand_range_pitch = [-15,15]
rand_range_yaw = [-180,180]

x_segment  = [0.05,0.95]
y_segment = [0.05,0.95]
z_segment = [0.0,0.5]

classes = [0,1,2]
